### ISSUE TITLE
Reset selected date

### ISSUE THREAD

**Issue by djabif** [HalleyAssist/ion-range-calendar#24]
Hi, how can I visually reset the selected dates?
This is my `ion-range-calendar` 

```
 <ion-range-calendar
            [ngClass]="{ 'single-date': dateRange.from === dateRange.to }"
            [(ngModel)]="dateRange"
            [options]="optionsRange"
            (selectStart)="onSelectStart($event)"
            [type]="type"
            [format]="'YYYY-MM-DD'">
</ion-range-calendar>
```

And I have a click event to clear the date selection:
```
 this.dateRange = {
      from: undefined,
      to: undefined
    };
```
The calendar dateRange is set to undefined but the calendar UI is not updated.
Thanks

**Comment by djabif** [comment]
Hi @Googlproxer thank you so much for updating the library :) 
 
I see you have a fix in 17.0.4 to allow undefined  values but you didn't publish that version. Latest version on npm is 17.0.3, do you have any estimate when you will be publishing it? 
Thanks again for all your work.

**Comment by splitice** [comment]
This is but a fork. We are not the official maintainers.

**Comment by djabif** [comment]
Thank you very much for the updated. Reset works perfect now ❤️
