### ISSUE TITLE
Specifying { from: 0 } in options renders component unusable

### ISSUE THREAD

**Issue by toalmoal** [HalleyAssist/ion-range-calendar#32]
Hi,

I am trying to allow date selection in the past. I have setup the options as:

```
options: CalendarComponentOptions = {
    from: 0
};
```
However, date selection gets completely disabled with this option.

**Comment by zaidkatbeh** [comment]
any updates on this?

**Comment by Googlproxer** [comment]
This is fixed in `18.0.0`
