### ISSUE TITLE
ngmodel didn't reflect auto update calendar

### ISSUE THREAD

**Issue by indrapalijama** [HalleyAssist/ion-range-calendar#34]
currently i've been implemented this with version 1.4.0 because i'm using ionic with angular 16
it works just fine, but when i already selected the date-range in calendar, when i opened it again, the calendar's UI didn't reflect to the ngmodel that provided

**Comment by zaidkatbeh** [comment]
I don't know if I understand you correctly , but i had a problem where i update the dates that i pass to ngmodal and the calendar didn't reflect that, and i fixed it by using ChangeDetectorRef, like this:
first inject it  
  constructor(private cdRef: ChangeDetectorRef) { }

then after the updates call the detectChanges method
      this.cdRef.detectChanges();

**Comment by indrapalijama** [comment]
> I don't know if I understand you correctly , but i had a problem where i update the dates that i pass to ngmodal and the calendar didn't reflect that, and i fixed it by using ChangeDetectorRef, like this: first inject it constructor(private cdRef: ChangeDetectorRef) { }
> 
> then after the updates call the detectChanges method this.cdRef.detectChanges();


Hi, I already did based on your suggestion but somehow it still didn't work. Attached below is my code:

HTML:
```html
<ion-item lines="none">
  <ion-input (click)="openCalendar()" class="custom-input" formControlName="EXAMPLE_DATE"
    [class.invalid]="getControl('EXAMPLE_DATE').invalid && getControl('EXAMPLE_DATE').touched"
    placeholder="Example Date" type="string" [(ngModel)]="example_date">
  </ion-input>
</ion-item>
```

TypeScript:
```typescript
async openCalendar() {
  this.cdRef.detectChanges();
  const options: CalendarModalOptions = {
    pickMode: "range",
    title: 'Initiate Date',
    clearLabel: "",
    clearIcon: true,
    from: startOfMonth(new Date())
  };

  const myCalendar = await this.modalCtrl.create({
    component: CalendarModal,
    componentProps: { options }
  });

  myCalendar.present();

  const event = await myCalendar.onDidDismiss();

  if (event.role === "done") {
    const date = event.data;
    const from: CalendarResult = date.from;
    const to: CalendarResult = date.to;
    this.example_date = {
      from: from.string,
      to: to.string
    };
  }
}
```
can you see that if it something that i missed?

**Comment by zaidkatbeh** [comment]
i think you are calling cdRef.detectChanges() before you actually  updating the value, you should call it after.

**Comment by indrapalijama** [comment]
> i think you are calling cdRef.detectChanges() before you actually updating the value, you should call it after.

you mean like this?
Fixed code:
```typescript
async openCalendar() {
  const options: CalendarModalOptions = {
    pickMode: "range",
    title: 'Initiate Date',
    clearLabel: "",
    clearIcon: true,
    from: startOfMonth(new Date())
  };

  const myCalendar = await this.modalCtrl.create({
    component: CalendarModal,
    componentProps: { options }
  });

  myCalendar.present();

  const event = await myCalendar.onDidDismiss();

  if (event.role === "done") {
    const date = event.data;
    const from: CalendarResult = date.from;
    const to: CalendarResult = date.to;
    this.example_date = {
      from: from.string,
      to: to.string
    };
    this.cdRef.detectChanges();
  }
}
```
still not working tho, my input in html shows as "[object Object]" instead of date, is there something that i still missing in my code?

**Comment by zaidkatbeh** [comment]
ion input cannot render objects, you can try printing it in a <p> or somthing like <p>{{example_date.from}}-{{example_date.to}}</p>

**Comment by indrapalijama** [comment]
> ion input cannot render objects, you can try printing it in a
> 
> or somthing like
> 
> {{example_date.from}}-{{example_date.to}}

hey, thanks for your help zaid!
i think i just solved my problem
i'm using "defaultDateRange" in modalOptions
here's my complete code :
Fixed code:
```typescript
let example_date_show: string;
async openCalendar() {
  const options: CalendarModalOptions = {
    pickMode: "range",
    title: 'Initiate Date',
    clearLabel: "",
    clearIcon: true,
    from: startOfMonth(new Date()),
     defaultDateRange: this.init_date
  };

  const myCalendar = await this.modalCtrl.create({
    component: CalendarModal,
    componentProps: { options }
  });

  myCalendar.present();

  const event = await myCalendar.onDidDismiss();

  if (event.role === "done") {
    const date = event.data;
    const from: CalendarResult = date.from;
    const to: CalendarResult = date.to;
    this.example_date = {
      from: from.string,
      to: to.string
    };
    this.example_date_show = `${from.string} to ${to.string}`;
    this.cdRef.detectChanges();
  }
}
```
my ngmodel in html is using example_date_show
